repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies:
          [
            alembic,
            fastapi,
            pydantic,
            redis,
            "sqlalchemy[mypy]==1.4.37",
            sqlalchemy2-stubs,
            typer,
            types-redis,
          ]
        args: ["--strict"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--ignore=E203,E501,W503"]
        additional_dependencies: [flake8-commas, flake8-debugger, flake8-print]
        exclude: bdd

default_language_version:
  python: python3.12
