version: '3'
services:
  app:
    image: seongr39/ttm
    platform: linux/amd64
    container_name: TTM-app
    ports:
      - "80:80"

  redis:
    image: redis
    container_name: TTM-redis
    ports:
      - "6379:6379"

networks:
  backend:
