name: EC2 Docker Alembic Migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: master

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: EC2 Docker Alembic Migration
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          CONTAINER_ID=$(docker ps -qf "name=TTM-app")

          if [ -z "$CONTAINER_ID" ]; then
            echo "Container is not running."
            exit 1
          fi

          echo "docker exec $CONTAINER_ID poetry run alembic upgrade head"
