name: Auto-delete Branch After Merge

on:
  push:
    branches:
      - main

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check if branch is merged
      run: |
        branch_name=$(jq -r .ref <<< "$GITHUB_EVENT_PATH")
        merged=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls?state=closed | jq ".[] | select(.base.ref == \"main\" and .head.ref == \"$branch_name\")")
        if [[ -n "$merged" ]]; then
          echo "Branch is merged. Deleting $branch_name."
          git fetch --all
          git branch -d "$branch_name"
          git push origin --delete "$branch_name"
        else
          echo "Branch is not merged. No action needed."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
