name: Unit tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up resources
      run: |
        docker compose -f docker/docker-compose-local.yml up -d

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'

    - name: Set up Poetry 1.6.1
      run: curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run make test
        poetry run coverage json

    - uses: actions/upload-artifact@v3
      with:
        name: test-result
        path: coverage.json
