name: Unit tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up resources
      run: |
        docker compose -f docker/docker-compose-local.yml up

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'

    - name: Install dependencies
      run: |
        make install

    - name: Run tests
      run: |
        make test
